# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

admin_email = 'admin@elasticpersonas.ca'
if !Account.find_by_email(admin_email).present?
Account.create!(your_name: 'Super Admin', email: admin_email, password: 'password@123',
                password_confirmation: 'password@123', confirmed_at: Time.now, admin: true,
                company_name: 'Elastic Personas', company_email: admin_email)
end

profiles_array =
["Survey is sent (made by me)",
 "Survey is sent (made by others)",
 "Survey expired (made by me)",
 "Survey expired (made by others)",
 "Survey is completed (made by me)",
 "Survey is completed (made by others)",
 "We have special offers",
 "New features released",
 "There’s a revision for my account",
 "There’s an update for my account",
 "Don't send me any email"
 ]
profiles_array.each do |x|
  EmailNotificationType.find_or_create_by(title: x)
end


# industry_list =
#   [["Accounting\n", 0],
#    ["Airlines/Aviation\n", 1],
#    ["Alternative Dispute Resolution\n", 2],
#    ["Alternative Medicine\n", 3],
#    ["Animation\n", 4],
#    ["Apparel & Fashion\n", 5],
#    ["Architecture & Planning\n", 6],
#    ["Arts & Crafts\n", 7],
#    ["Automotive\n", 8],
#    ["Aviation & Aerospace\n", 9],
#    ["Banking\n", 10],
#    ["Biotechnology\n", 11],
#    ["Broadcast Media\n", 12],
#    ["Building Materials\n", 13],
#    ["Business Supplies & Equipment\n", 14],
#    ["Capital Markets\n", 15],
#    ["Chemicals\n", 16],
#    ["Civic & Social Organization\n", 17],
#    ["Civil Engineering\n", 18],
#    ["Commercial Real Estate\n", 19],
#    ["Computer & Network Security\n", 20],
#    ["Computer Games\n", 21],
#    ["Computer Hardware\n", 22],
#    ["Computer Networking\n", 23],
#    ["Computer Software\n", 24],
#    ["Construction\n", 25],
#    ["Consumer Electronics\n", 26],
#    ["Consumer Goods\n", 27],
#    ["Consumer Services\n", 28],
#    ["Cosmetics\n", 29],
#    ["Dairy\n", 30],
#    ["Defense & Space\n", 31],
#    ["Design\n", 32],
#    ["Education Management\n", 33],
#    ["E-learning\n", 34],
#    ["Electrical & Electronic Manufacturing\n", 35],
#    ["Entertainment\n", 36],
#    ["Environmental Services\n", 37],
#    ["Events Services\n", 38],
#    ["Executive Office\n", 39],
#    ["Facilities Services\n", 40],
#    ["Farming\n", 41],
#    ["Financial Services\n", 42],
#    ["Fine Art\n", 43],
#    ["Fishery\n", 44],
#    ["Food & Beverages\n", 45],
#    ["Food Production\n", 46],
#    ["Fundraising\n", 47],
#    ["Furniture\n", 48],
#    ["Gambling & Casinos\n", 49],
#    ["Glass, Ceramics & Concrete\n", 50],
#    ["Government Administration\n", 51],
#    ["Government Relations\n", 52],
#    ["Graphic Design\n", 53],
#    ["Health, Wellness & Fitness\n", 54],
#    ["Higher Education\n", 55],
#    ["Hospital & Health Care\n", 56],
#    ["Hospitality\n", 57],
#    ["Human Resources\n", 58],
#    ["Import & Export\n", 59],
#    ["Individual & Family Services\n", 60],
#    ["Industrial Automation\n", 61],
#    ["Information Services\n", 62],
#    ["Information Technology & Services\n", 63],
#    ["Insurance\n", 64],
#    ["International Affairs\n", 65],
#    ["International Trade & Development\n", 66],
#    ["Internet\n", 67],
#    ["Investment Banking/Venture\n", 68],
#    ["Investment Management\n", 69],
#    ["Judiciary\n", 70],
#    ["Law Enforcement\n", 71],
#    ["Law Practice\n", 72],
#    ["Legal Services\n", 73],
#    ["Legislative Office\n", 74],
#    ["Leisure & Travel\n", 75],
#    ["Libraries\n", 76],
#    ["Logistics & Supply Chain\n", 77],
#    ["Luxury Goods & Jewelry\n", 78],
#    ["Machinery\n", 79],
#    ["Management Consulting\n", 80],
#    ["Maritime\n", 81],
#    ["Marketing & Advertising\n", 82],
#    ["Market Research\n", 83],
#    ["Mechanical or Industrial Engineering\n", 84],
#    ["Media Production\n", 85],
#    ["Medical Device\n", 86],
#    ["Medical Practice\n", 87],
#    ["Mental Health Care\n", 88],
#    ["Military\n", 89],
#    ["Mining & Metals\n", 90],
#    ["Motion Pictures & Film\n", 91],
#    ["Museums & Institutions\n", 92],
#    ["Music\n", 93],
#    ["Nanotechnology\n", 94],
#    ["Newspapers\n", 95],
#    ["Nonprofit Organization Management\n", 96],
#    ["Oil & Energy\n", 97],
#    ["Online Publishing\n", 98],
#    ["Outsourcing/Offshoring\n", 99],
#    ["Package/Freight Delivery\n", 100],
#    ["Packaging & Containers\n", 101],
#    ["Paper & Forest Products\n", 102],
#    ["Performing Arts\n", 103],
#    ["Pharmaceuticals\n", 104],
#    ["Philanthropy\n", 105],
#    ["Photography\n", 106],
#    ["Plastics\n", 107],
#    ["Political Organization\n", 108],
#    ["Primary/Secondary Education\n", 109],
#    ["Printing\n", 110],
#    ["Professional Training\n", 111],
#    ["Program Development\n", 112],
#    ["Public Policy\n", 113],
#    ["Public Relations\n", 114],
#    ["Public Safety\n", 115],
#    ["Publishing\n", 116],
#    ["Railroad Manufacture\n", 117],
#    ["Ranching\n", 118],
#    ["Real Estate\n", 119],
#    ["Recreational\n", 120],
#    ["Facilities & Services\n", 121],
#    ["Religious Institutions\n", 122],
#    ["Renewables & Environment\n", 123],
#    ["Research\n", 124],
#    ["Restaurants\n", 125],
#    ["Retail\n", 126],
#    ["Security & Investigations\n", 127],
#    ["Semiconductors\n", 128],
#    ["Shipbuilding\n", 129],
#    ["Sporting Goods\n", 130],
#    ["Sports\n", 131],
#    ["Staffing & Recruiting\n", 132],
#    ["Supermarkets\n", 133],
#    ["Telecommunications\n", 134],
#    ["Textiles\n", 135],
#    ["Think Tanks\n", 136],
#    ["Tobacco\n", 137],
#    ["Translation & Localization\n", 138],
#    ["Transportation/Trucking/Railroad\n", 139],
#    ["Utilities\n", 140],
#    ["Venture Capital\n", 141],
#    ["Veterinary\n", 142],
#    ["Warehousing\n", 143],
#    ["Wholesale\n", 144],
#    ["Wine & Spirits\n", 145],
#    ["Wireless\n", 146],
#    ["Writing & Editing", 147]]


# industry_list.each do |i|
#   if !Industry.find_by_slug_id(i).present?
#     Industry.create(title: i[0], slug_id: i[1])
#   end
# end
